from __future__ import annotations

import json
import os
import shutil
import subprocess
import threading
import time
import uuid
from concurrent.futures import ThreadPoolExecutor
from pathlib import Path
from typing import Any

from fastapi import FastAPI, File, Form, HTTPException, UploadFile
from fastapi.responses import FileResponse, HTMLResponse
from fastapi.staticfiles import StaticFiles
from fastapi.templating import Jinja2Templates
from starlette.requests import Request

APP_DIR = Path(__file__).resolve().parent
DATA_DIR = Path(os.getenv("VIDEOEDITOR_DATA_DIR", "data")).resolve()
MAX_UPLOAD_BYTES = int(os.getenv("MAX_UPLOAD_MB", "500")) * 1024 * 1024
WORKER_COUNT = max(1, int(os.getenv("MAX_RENDER_WORKERS", "1")))
ALLOWED_VIDEO_EXTENSIONS = {".mp4", ".mov", ".m4v", ".webm", ".mkv", ".avi"}
ALLOWED_SUBTITLE_EXTENSIONS = {".srt"}
OUTPUT_PRESETS = {
    "landscape": (1280, 720),
    "portrait": (720, 1280),
    "square": (1080, 1080),
}

DATA_DIR.mkdir(parents=True, exist_ok=True)
JOBS: dict[str, dict[str, Any]] = {}
JOBS_LOCK = threading.Lock()
EXECUTOR = ThreadPoolExecutor(max_workers=WORKER_COUNT, thread_name_prefix="video-render")

app = FastAPI(title="VideoEditor", version="0.1.0")
app.mount("/static", StaticFiles(directory=APP_DIR / "static"), name="static")
templates = Jinja2Templates(directory=APP_DIR / "templates")


def _tool_path(name: str) -> str | None:
    return shutil.which(name)


def _run_probe(video_path: Path) -> dict[str, Any]:
    ffprobe = _tool_path("ffprobe")
    if not ffprobe:
        raise RuntimeError("ffprobe is not installed. Run the app with Docker or install FFmpeg.")
    result = subprocess.run(
        [
            ffprobe, "-v", "error", "-show_entries",
            "format=duration:stream=codec_type,width,height,duration",
            "-of", "json", str(video_path),
        ],
        capture_output=True, text=True, timeout=30, check=False,
    )
    if result.returncode != 0:
        raise RuntimeError("This file could not be read as a video.")
    try:
        metadata = json.loads(result.stdout)
    except json.JSONDecodeError as exc:
        raise RuntimeError("Could not read video metadata.") from exc
    duration = float((metadata.get("format") or {}).get("duration") or 0)
    if duration <= 0:
        durations = [
            float(stream.get("duration") or 0)
            for stream in metadata.get("streams", [])
            if stream.get("codec_type") == "video"
        ]
        duration = max(durations, default=0)
    if duration <= 0:
        raise RuntimeError("The uploaded file has no readable duration.")
    return {"duration": duration, "metadata": metadata}


def _update_job(job_id: str, **values: Any) -> None:
    with JOBS_LOCK:
        if job_id in JOBS:
            JOBS[job_id].update(values)


def _escape_subtitle_filter_path(path: Path) -> str:
    # The render directory is generated by this app. Escaping protects filter syntax.
    value = path.as_posix()
    return value.replace("\\", "\\\\").replace(":", "\\:").replace("'", "\\'").replace(",", "\\,").replace("[", "\\[").replace("]", "\\]")


def _render(job_id: str, folder: Path, source: Path, duration: float,
            start: float, end: float, preset: str, subtitle_path: Path | None) -> None:
    output = folder / "rendered.mp4"
    log_path = folder / "ffmpeg.log"
    try:
        ffmpeg = _tool_path("ffmpeg")
        if not ffmpeg:
            raise RuntimeError("FFmpeg is not installed. Run the app with Docker or install FFmpeg.")

        width, height = OUTPUT_PRESETS[preset]
        filters = [
            f"scale={width}:{height}:force_original_aspect_ratio=decrease",
            f"pad={width}:{height}:(ow-iw)/2:(oh-ih)/2",
            "setsar=1",
        ]
        if subtitle_path:
            filters.append(f"subtitles='{_escape_subtitle_filter_path(subtitle_path)}'")
        filters.append("format=yuv420p")

        command = [
            ffmpeg, "-hide_banner", "-y", "-ss", f"{start:.3f}", "-i", str(source),
            "-t", f"{end - start:.3f}", "-vf", ",".join(filters),
            "-c:v", "libx264", "-preset", "veryfast", "-crf", "23",
            "-c:a", "aac", "-b:a", "128k", "-movflags", "+faststart",
            "-progress", "pipe:1", "-nostats", str(output),
        ]

        _update_job(job_id, status="rendering", progress=1, message="Rendering video with FFmpeg.")
        began = time.monotonic()
        with log_path.open("w", encoding="utf-8") as errlog:
            process = subprocess.Popen(
                command, stdout=subprocess.PIPE, stderr=errlog,
                text=True, bufsize=1,
            )
            assert process.stdout is not None
            for raw_line in process.stdout:
                line = raw_line.strip()
                if line.startswith("out_time_us="):
                    try:
                        elapsed_us = int(line.split("=", 1)[1])
                        render_seconds = elapsed_us / 1_000_000
                        progress = 2 + min(96, (render_seconds / max(end - start, 0.001)) * 96)
                        _update_job(job_id, progress=round(progress), elapsed_seconds=round(time.monotonic() - began, 1))
                    except ValueError:
                        continue
                elif line == "progress=end":
                    _update_job(job_id, progress=99, message="Finalizing MP4.")
            return_code = process.wait(timeout=max(600, (end - start) * 20))
        if return_code != 0 or not output.exists() or output.stat().st_size < 1024:
            details = log_path.read_text(encoding="utf-8", errors="replace")[-1800:]
            raise RuntimeError("FFmpeg could not render this video. " + details[-900:])

        # Probe the output before advertising it as complete.
        _run_probe(output)
        _update_job(
            job_id, status="completed", progress=100, message="Video rendered successfully.",
            output_name=output.name, output_size=output.stat().st_size,
            completed_at=time.time(),
        )
    except subprocess.TimeoutExpired:
        _update_job(job_id, status="failed", message="Render timed out. Try a shorter clip.")
    except Exception as exc:
        _update_job(job_id, status="failed", message=str(exc)[:1200])
    finally:
        # Source assets are retained temporarily for debugging and re-renders.
        _update_job(job_id, finished=True)


@app.get("/", response_class=HTMLResponse)
async def home(request: Request) -> HTMLResponse:
    return templates.TemplateResponse(request, "index.html", {"request": request})


@app.get("/api/health")
async def health() -> dict[str, Any]:
    ffmpeg = _tool_path("ffmpeg")
    ffprobe = _tool_path("ffprobe")
    return {
        "status": "ok" if ffmpeg and ffprobe else "degraded",
        "ffmpeg_available": bool(ffmpeg),
        "ffprobe_available": bool(ffprobe),
        "render_workers": WORKER_COUNT,
        "max_upload_mb": MAX_UPLOAD_BYTES // (1024 * 1024),
    }


@app.post("/api/jobs", status_code=202)
async def create_job(
    video: UploadFile = File(...),
    start_seconds: float = Form(0),
    end_seconds: float | None = Form(None),
    aspect_ratio: str = Form("landscape"),
    subtitles: UploadFile | None = File(None),
) -> dict[str, Any]:
    if not _tool_path("ffmpeg") or not _tool_path("ffprobe"):
        raise HTTPException(status_code=503, detail="FFmpeg is unavailable. Start the app with Docker.")
    if not video.filename:
        raise HTTPException(status_code=400, detail="Choose a video file.")
    if Path(video.filename).suffix.lower() not in ALLOWED_VIDEO_EXTENSIONS:
        raise HTTPException(status_code=415, detail="Use MP4, MOV, M4V, WebM, MKV, or AVI video.")
    if aspect_ratio not in OUTPUT_PRESETS:
        raise HTTPException(status_code=400, detail="Choose landscape, portrait, or square output.")
    if start_seconds < 0 or (end_seconds is not None and end_seconds <= start_seconds):
        raise HTTPException(status_code=400, detail="End time must be greater than start time.")

    job_id = uuid.uuid4().hex
    folder = DATA_DIR / job_id
    folder.mkdir(parents=True, exist_ok=False)
    source = folder / ("source" + Path(video.filename).suffix.lower())
    bytes_written = 0

    try:
        with source.open("wb") as target:
            while True:
                chunk = await video.read(1024 * 1024)
                if not chunk:
                    break
                bytes_written += len(chunk)
                if bytes_written > MAX_UPLOAD_BYTES:
                    raise HTTPException(status_code=413, detail=f"Video exceeds the {MAX_UPLOAD_BYTES // (1024 * 1024)} MB upload limit.")
                target.write(chunk)
    except Exception:
        shutil.rmtree(folder, ignore_errors=True)
        raise
    finally:
        await video.close()

    if bytes_written == 0:
        shutil.rmtree(folder, ignore_errors=True)
        raise HTTPException(status_code=400, detail="The uploaded video is empty.")

    subtitle_path: Path | None = None
    if subtitles and subtitles.filename:
        if Path(subtitles.filename).suffix.lower() not in ALLOWED_SUBTITLE_EXTENSIONS:
            shutil.rmtree(folder, ignore_errors=True)
            raise HTTPException(status_code=415, detail="Subtitles must be an .srt file.")
        subtitle_path = folder / "captions.srt"
        try:
            subtitle_bytes = await subtitles.read()
            if len(subtitle_bytes) > 5 * 1024 * 1024:
                raise HTTPException(status_code=413, detail="Subtitle file exceeds 5 MB.")
            # SRT is text. Reject binary or invalid UTF-8 rather than passing it to FFmpeg.
            subtitle_bytes.decode("utf-8-sig")
            subtitle_path.write_bytes(subtitle_bytes)
        except UnicodeDecodeError as exc:
            shutil.rmtree(folder, ignore_errors=True)
            raise HTTPException(status_code=400, detail="Subtitle file must be UTF-8 encoded.") from exc
        except Exception:
            shutil.rmtree(folder, ignore_errors=True)
            raise
        finally:
            await subtitles.close()

    try:
        probe = _run_probe(source)
    except Exception as exc:
        shutil.rmtree(folder, ignore_errors=True)
        raise HTTPException(status_code=422, detail=str(exc)) from exc

    duration = probe["duration"]
    start_seconds = float(start_seconds)
    end_seconds = duration if end_seconds is None or end_seconds == 0 else float(end_seconds)
    if start_seconds >= duration or end_seconds > duration + 0.05:
        shutil.rmtree(folder, ignore_errors=True)
        raise HTTPException(status_code=400, detail=f"Trim points must be within the video duration ({duration:.2f} seconds).")
    end_seconds = min(end_seconds, duration)
    if end_seconds - start_seconds < 0.25:
        shutil.rmtree(folder, ignore_errors=True)
        raise HTTPException(status_code=400, detail="Select a clip at least 0.25 seconds long.")

    job = {
        "id": job_id, "status": "queued", "progress": 0, "message": "Waiting for a render worker.",
        "source_name": Path(video.filename).name, "source_duration": round(duration, 2),
        "start_seconds": start_seconds, "end_seconds": end_seconds,
        "aspect_ratio": aspect_ratio, "created_at": time.time(),
    }
    with JOBS_LOCK:
        JOBS[job_id] = job
    EXECUTOR.submit(_render, job_id, folder, source, duration, start_seconds, end_seconds, aspect_ratio, subtitle_path)
    return {"id": job_id, "status": "queued", "duration": round(duration, 2), "status_url": f"/api/jobs/{job_id}"}


@app.get("/api/jobs/{job_id}")
async def get_job(job_id: str) -> dict[str, Any]:
    with JOBS_LOCK:
        job = JOBS.get(job_id)
        if not job:
            raise HTTPException(status_code=404, detail="Render job not found. Jobs reset when the server restarts.")
        result = dict(job)
    result.pop("finished", None)
    if result.get("status") == "completed":
        result["download_url"] = f"/api/jobs/{job_id}/download"
        result["output_size_mb"] = round(result.get("output_size", 0) / (1024 * 1024), 2)
    result.pop("output_size", None)
    return result


@app.get("/api/jobs/{job_id}/download")
async def download_job(job_id: str) -> FileResponse:
    with JOBS_LOCK:
        job = JOBS.get(job_id)
        if not job or job.get("status") != "completed":
            raise HTTPException(status_code=404, detail="The rendered video is not ready.")
    output = DATA_DIR / job_id / "rendered.mp4"
    if not output.is_file():
        raise HTTPException(status_code=404, detail="Rendered file is no longer available.")
    safe_name = Path(job["source_name"]).stem[:80] or "video"
    return FileResponse(output, media_type="video/mp4", filename=f"{safe_name}-edited.mp4")
